BEGIN;
--
-- Create model Student
--
CREATE TABLE "users_student" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "student_id" varchar(20) NOT NULL, "first_name" varchar(20) NOT NULL, "second_name" varchar(20) NOT NULL, "last_name" varchar(20) NOT NULL, "faculty" varchar NOT NULL, "account_balance" numeric(20, 6) NOT NULL);
COMMIT;
