# Generated by Django 6.0.6 on 2026-06-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_teachers_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.teacher')),
            ],
        ),
    ]
