# Generated by Django 6.0.6 on 2026-06-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_faculty_dean'),
        ('users', '0005_remove_student_faculty_remove_teacher_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.teacher'),
        ),
    ]
