# Generated by Django 6.0.6 on 2026-06-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_faculty_dean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
    ]
