# Generated by Django 6.0.6 on 2026-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('faculty', models.CharField()),
                ('salary', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
    ]
