# Generated by Django 6.0.6 on 2026-06-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0003_rename_teachers_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.faculty'),
        ),
    ]
