# Generated by Django 6.0.6 on 2026-06-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_teacher_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='faculty',
        ),
    ]
