# Generated by Django 6.0.6 on 2026-06-24 08:11

import branches.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_faculty_dean'),
        ('users', '0006_teacher_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(default=branches.models.Faculty.get_default_faculty, on_delete=django.db.models.deletion.CASCADE, to='branches.faculty'),
        ),
    ]
